# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ui_MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenuWindow(object):
    def setupUi(self, MainMenuWindow):
        MainMenuWindow.setObjectName("MainMenuWindow")
        MainMenuWindow.resize(800, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainMenuWindow.sizePolicy().hasHeightForWidth())
        MainMenuWindow.setSizePolicy(sizePolicy)
        MainMenuWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainMenuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Manrope ExtraBold")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.btn_play = HoveringButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_play.sizePolicy().hasHeightForWidth())
        self.btn_play.setSizePolicy(sizePolicy)
        self.btn_play.setMinimumSize(QtCore.QSize(200, 70))
        font = QtGui.QFont()
        font.setFamily("Manrope")
        font.setPointSize(15)
        self.btn_play.setFont(font)
        self.btn_play.setStyleSheet("")
        self.btn_play.setObjectName("btn_play")
        self.verticalLayout.addWidget(self.btn_play, 0, QtCore.Qt.AlignHCenter)
        self.bottom_buttons = QtWidgets.QHBoxLayout()
        self.bottom_buttons.setObjectName("bottom_buttons")
        self.github_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.github_button.sizePolicy().hasHeightForWidth())
        self.github_button.setSizePolicy(sizePolicy)
        self.github_button.setMinimumSize(QtCore.QSize(50, 50))
        self.github_button.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setKerning(True)
        self.github_button.setFont(font)
        self.github_button.setStyleSheet("    background-color: transparent;\n"
"    border: none;")
        self.github_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\icons/github_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.github_button.setIcon(icon)
        self.github_button.setIconSize(QtCore.QSize(40, 40))
        self.github_button.setObjectName("github_button")
        self.bottom_buttons.addWidget(self.github_button, 0, QtCore.Qt.AlignBottom)
        self.settings_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_button.sizePolicy().hasHeightForWidth())
        self.settings_button.setSizePolicy(sizePolicy)
        self.settings_button.setMinimumSize(QtCore.QSize(50, 50))
        self.settings_button.setMaximumSize(QtCore.QSize(50, 50))
        self.settings_button.setStyleSheet("    background-color: transparent;\n"
"    border: none;")
        self.settings_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\ui\\icons/settings_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_button.setIcon(icon1)
        self.settings_button.setIconSize(QtCore.QSize(40, 40))
        self.settings_button.setObjectName("settings_button")
        self.bottom_buttons.addWidget(self.settings_button, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout.addLayout(self.bottom_buttons)
        MainMenuWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainMenuWindow)
        QtCore.QMetaObject.connectSlotsByName(MainMenuWindow)

    def retranslateUi(self, MainMenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MainMenuWindow.setWindowTitle(_translate("MainMenuWindow", "MainWindow"))
        self.label.setText(_translate("MainMenuWindow", "Ultimate\n"
"TicTacToe"))
        self.btn_play.setText(_translate("MainMenuWindow", "play"))
        self.github_button.setToolTip(_translate("MainMenuWindow", "Страница проекта на GitHub"))
from CustomButtons import HoveringButton
