# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\ui\ui_WinWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Игра окончена")
        MainWindow.resize(200, 90)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(200, 90))
        self.centralwidget.setMaximumSize(QtCore.QSize(200, 89))
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.winner_label = QtWidgets.QLabel(self.centralwidget)
        self.winner_label.setGeometry(QtCore.QRect(10, 40, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setBold(True)
        font.setWeight(75)
        self.winner_label.setFont(font)
        self.winner_label.setObjectName("winner_label")
        self.save_game_btn = HoveringButton(self.centralwidget)
        self.save_game_btn.setGeometry(QtCore.QRect(50, 60, 111, 23))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.save_game_btn.setFont(font)
        self.save_game_btn.setObjectName("save_game_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Игра окончена!"))
        self.winner_label.setText(_translate("MainWindow", "Победитель:"))
        self.save_game_btn.setText(_translate("MainWindow", "сохранить игру"))
from CustomButtons import HoveringButton
